### ISSUE TITLE
For Cud

### ISSUE THREAD

**Issue by Alexey-T** [Kristinita/SashaSublime#2]
Hi. maybe possible to draw the same theme for CudaText? Will be 1st theme which is devoted to a human in CT =)

**Comment by Kristinita** [comment]
__Maybe, but hardly.__

Hello and sorry for the answer. I planned to port SashaSublime to another IDE and text editors, but I haven't a time for it :cry: .

But:

1. SashaSublime is open source,
1. In code, I add comments for each parameter.

You or another user can port SashaSublime for any IDE or text editor.

Thanks.
